name: Telegram userbot

on:
  push:
  workflow_dispatch:
    
jobs:
  Userbot:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Set Git Configs & Secrets
         run: |
           git config --global user.email "${{ secrets.GHMAIL }}"
           git config --global user.name "${{ secrets.GHUSER }}"
           echo "https://${{ secrets.GHUSER }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

       - name: Cloning repo
         continue-on-error: false
         run: |
           git clone https://${{ secrets.GHUSER }}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.REPO }} ubot

       - name: Running Bot
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd ubot
           echo "${{ secrets.DPASS }}" | docker login -u rahulkhatri137 --password-stdin
           docker container prune --force || true
           docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t ubot
           docker image ls
           docker run --privileged --rm -i ubot

       - name: Loop workflow
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
           cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > loop.txt
           git add loop.txt
           git commit -m "Workflow : Loop"
           git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
